### ISSUE TITLE
Please add support to OpenRouter

### ISSUE THREAD

**Issue by chugor** [wandb/openui#204]
OpenRouter is very popular too.
Please add support to it.
Huge thanks !

**Comment by vanpelt** [comment]
Hey @chugor you can use [LiteLLM](https://github.com/wandb/openui?tab=readme-ov-file#litellm) to talk to any 3rd party model provider.  I've also added a simple integration where you could set the following environment variables with the latest docker image and it should list the models you have available to you from OpenRouter:

```shell
OPENAI_COMPATIBLE_ENDPOINT=https://openrouter.ai/api/v1
OPENAI_COMPATIBLE_API_KEY=$OPENROUTER_API_KEY
```

This will list all models supported by OpenRouter which will be a very long list.  If you wanted to only include a handful of selected models you can pass a custom litellm config as described in the README, something like:

```yaml
model_list:
  - model_name: meta-llama/llama-3.1-8b-instruct
     litellm_params:
       model: openai/meta-llama/llama-3.1-8b-instruct
       api_key: "os.environ/OPENROUTER_API_KEY"
       base_url: https://openrouter.ai/api/v1
```
