### ISSUE TITLE
Can´t Use it with VERTEX AI

### ISSUE THREAD

**Issue by everaldo** [wandb/openui#209]
Got this error:

![Image](https://github.com/user-attachments/assets/b6abca03-effa-43e2-bf2c-80122485aa91)

Error! 400 Error code: 400 - {'error': {'message': 'litellm.BadRequestError: VertexAIException BadRequestError - vertexai import failed please run `pip install -U google-cloud-aiplatform "anthropic[vertex]"`\nReceived Model Group=claude-3-5-sonnet\nAvailable Model Group Fallbacks=None', 'type': None, 'param': None, 'code': '400'}}

My litellm-config.yaml

```
model_list:
  - model_name: claude-3-5-sonnet
    litellm_params:
      model: vertex_ai/claude-3-5-sonnet@20240620
      vertex_ai_project: os.environ/VERTEXAI_PROJECT
      vertex_ai_location: os.environ/VERTEXAI_LOCATION

```

I´ve also tried this:

```
 docker run --name openui-test -p 7878:7878   -e VERTEXAI_PROJECT   -e VERTEXAI_LOCATION   -e GOOGLE_APPLICATION_CREDENTIALS   -v $(pwd)/openui_data/litellm-config.yaml:/app/litellm-config.yaml -v $(pwd)/openui_data/application_default_credentials.json:/app/application_default_credentials.json   --entrypoint /bin/bash   ghcr.io/wandb/openui -c "pip install -U google-cloud-aiplatform 'anthropic[vertex]' && python -m openui --litellm"
```

But it fails.
