### ISSUE TITLE
After installing docker with ollama why needed openai key?

### ISSUE THREAD

**Issue by debjit** [wandb/openui#71]
```
version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ${OLLAMA_VOLUME_PATH:-ollama}:/root/.ollama

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7878:7878"
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - OPENAI_API_KEY=xxx
    depends_on:
      - ollama
volumes:
  ollama:
  ```
  This is my docker compose file, nothing has changed.
  Now when I run this, 
  ```
  Error! 401 Error code: 401 - {'error': {'message': 'Incorrect API key provided: xxx. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
  ```
  This error is showing. Ollama is running on this port
